create table PROJECT(
     ID INT NOT NULL,
     NAME VARCHAR (50) NOT NULL,
     STATUS  CHAR(20)   NOT NULL,
     START_DATE  DATETIME NOT NULL,
     END_DATE   DATETIME NOT NULL ,
     DESCRIPTION VARCHAR(500) NOT NULL ,
     MILESTONES VARCHAR(500) ,
     PRIMARY KEY (ID)
);